openapi: 3.0.0
info:
  title: E-Commerce basic API's
  description: we have basic operations like registering a user and login
  version: 0.1.9
servers:
  - url: http://localhost:8080
    description: LOCAL SERVER 
  # - url: https://2524-157-38-120-27.ngrok-free.app
  #   description: NGROK SERVER 

paths:
  /auth/register:
    post:
      summary: Register a new user
      description: Endpoint to register a new user.
      requestBody:
        description: User registration data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: daksh
                email:
                  type: string
                  example: daksh@gmail.com
                password:
                  type: string
                  example: Daksh@123
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: daksh
                  email:
                    type: string
                    example: daksh@gmail.com
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
paths:          
  /auth/login:
    post:
      summary: User login
      description: Endpoint to authenticate a user.
      requestBody:
        description: User login data
        required: true
        content:
          application/json:   
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: moin@gmail.com
                password:
                  type: string
                  example: moin123
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid email or password"
        '500':
          description: Internal Server Error
components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
        password:
          type: string